declare module 'd3-scale-chromatic' {
    export const interpolateViridis: (t: number) => string;
    export const interpolatePlasma: (t: number) => string;
    export const interpolateInferno: (t: number) => string;
    export const interpolateMagma: (t: number) => string;
    export const interpolateCividis: (t: number) => string;
    export const interpolateTurbo: (t: number) => string;
    export const interpolateBlues: (t: number) => string;
    export const interpolateGreens: (t: number) => string;
    export const interpolateGreys: (t: number) => string;
    export const interpolateOranges: (t: number) => string;
    export const interpolatePurples: (t: number) => string;
    export const interpolateReds: (t: number) => string;
    export const interpolateRainbow: (t: number) => string;
    export const interpolateSinebow: (t: number) => string;
    export const interpolateCubehelixDefault: (t: number) => string;
    export const interpolateWarm: (t: number) => string;
    export const interpolateCool: (t: number) => string;
    export const interpolateBuGn: (t: number) => string;
    export const interpolateBuPu: (t: number) => string;
    export const interpolateGnBu: (t: number) => string;
    export const interpolateOrRd: (t: number) => string;
    export const interpolatePuBuGn: (t: number) => string;
    export const interpolatePuBu: (t: number) => string;
    export const interpolatePuRd: (t: number) => string;
    export const interpolateRdPu: (t: number) => string;
    export const interpolateYlGnBu: (t: number) => string;
    export const interpolateYlGn: (t: number) => string;
    export const interpolateYlOrBr: (t: number) => string;
    export const interpolateYlOrRd: (t: number) => string;
    
    export const schemeCategory10: string[];
    export const schemeAccent: string[];
    export const schemeDark2: string[];
    export const schemePaired: string[];
    export const schemePastel1: string[];
    export const schemePastel2: string[];
    export const schemeSet1: string[];
    export const schemeSet2: string[];
    export const schemeSet3: string[];
    export const schemeTableau10: string[];
    export const schemeBrBG: string[][];
    export const schemePRGn: string[][];
    export const schemePiYG: string[][];
    export const schemePuOr: string[][];
    export const schemeRdBu: string[][];
    export const schemeRdGy: string[][];
    export const schemeRdYlBu: string[][];
    export const schemeRdYlGn: string[][];
    export const schemeSpectral: string[][];
    export const schemeBlues: string[][];
    export const schemeGreens: string[][];
    export const schemeGreys: string[][];
    export const schemeOranges: string[][];
    export const schemePurples: string[][];
    export const schemeReds: string[][];
    export const schemeBuGn: string[][];
    export const schemeBuPu: string[][];
    export const schemeGnBu: string[][];
    export const schemeOrRd: string[][];
    export const schemePuBuGn: string[][];
    export const schemePuBu: string[][];
    export const schemePuRd: string[][];
    export const schemeRdPu: string[][];
    export const schemeYlGnBu: string[][];
    export const schemeYlGn: string[][];
    export const schemeYlOrBr: string[][];
    export const schemeYlOrRd: string[][];
}
